width = 20
height = 20
moving_period = 0.1
restart_time = 1.0

[colors]
snake = [0.8, 0.0, 0.0, 1.0]
background = [0.5, 0.5, 0.5, 1.0]
food = [0.0, 0.8, 0.0, 1.0]
borders = [0.0, 0.0, 0.0, 1.0]
game_over = [0.9, 0.0, 0.0, 0.5]